-- V1__init_db.sql
create table user_roles (
    user_id bigint not null,
    role varchar(255) check (role in ('ADMIN','USER')));

create table users (
    id bigint generated by default as identity,
    email varchar(255) not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id));

alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users